name: Terraform Destroy prod

on:
  workflow_dispatch:   # manual trigger from GitHub Actions UI

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  TF_WORKING_DIR: terraform-project/terraform-modules/3-tier-with-vault-cloudwatch-sns-multienvsetup/environments/prod

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::938822141717:role/github-actions-terraform-role
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
         VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
         VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
         TF_VAR_vault_address: ${{ secrets.VAULT_ADDR }}
         TF_VAR_vault_token: ${{ secrets.VAULT_TOKEN }}
