name: Terraform Dev

on:
  pull_request:
    paths:
      - 'terraform-project/terraform-modules/3-tier-with-vault-cloudwatch-sns-multienvsetup/environments/dev/**'
      - 'terraform-project/terraform-modules/3-tier-with-vault-cloudwatch-sns-multienvsetup/modules/**'
  push:
    branches: [main]
    paths:
      - 'terraform-project/terraform-modules/3-tier-with-vault-cloudwatch-sns-multienvsetup/environments/dev/**'
      - 'terraform-project/terraform-modules/3-tier-with-vault-cloudwatch-sns-multienvsetup/modules/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: ap-south-1
  TF_WORKING_DIR: terraform-project/terraform-modules/3-tier-with-vault-cloudwatch-sns-multienvsetup/environments/dev

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::938822141717:role/github-actions-terraform-role
          aws-region: ${{ env.AWS_REGION }}
     # - run: terraform fmt -check -recursive
      - run: terraform init
      - run: terraform validate
      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan | tee plan_output.txt
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      - name: Comment Plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('terraform-project/terraform-modules/3-tier-with-vault-cloudwatch-sns-multienvsetup/environments/dev/plan_output.txt', 'utf8').slice(0, 60000);
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Terraform Plan (dev)\n\`\`\`\n${plan}\n\`\`\``
            });
    #  - name: Terraform Apply
     #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #    run: terraform apply -auto-approve tfplan
   ##     env:
     #     VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
       #   VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
